require('sld.config.keymaps')
require('sld.config.lazy')
require('sld.config.options')
require('sld.config.theme')
require('sld.config.autocmd')
require('sld.config.colors')
require('sld.config.diagnostics')
